### ISSUE TITLE
error code 500

### ISSUE THREAD

**Issue by yreiter** [valentinfrlch/ha-gpt4vision#32]
**Describe the bug**

I'm getting error - status code 500

"Failed to call service script/new_script1. Validation error: Fetch failed with status code 500"

**To Reproduce**

1. Just run the script; which used to work
2. here is the script

alias: Script Chiller
sequence:
  - service: gpt4vision.image_analyzer
    metadata: {}
    data:
      provider: Anthropic
      include_filename: false
      target_width: 1280
      detail: high
      max_tokens: 100
      temperature: 0.5
      message: what red numbers do you see?
      image_entity:
        - camera.chiller
    response_variable: response
  - service: notify.mobile_app_iphone15****
    data:
      message: "{{response.response_text}}"
  - service: input_text.set_value
    data:
      value: "{{response.response_text}}"
    target:
      entity_id: input_text.gpt4vision_response
description: ""

**Version**

- [x] I am on the latest version

**Expected behavior**

**Screenshots**

![image](https://github.com/user-attachments/assets/e40de17d-25ca-40fc-b15f-9ab59ad616b5)

**Logs**
```
Paste relevant logs here

This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/gpt4vision/request_handlers.py:246
integration: GPT-4 Vision (documentation, issues)
First occurred: 15:03:36 (1 occurrences)
Last logged: 15:03:36

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 652, in _async_run
    return await self.script.async_run(script_vars, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1770, in async_run
    return await asyncio.shield(create_eager_task(run.async_run()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 465, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 529, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 559, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 527, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 764, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 727, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2731, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2774, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/gpt4vision/__init__.py", line 223, in image_analyzer
    image_data = await client.fetch(image_url)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/gpt4vision/request_handlers.py", line 246, in fetch
    raise ServiceValidationError(
homeassistant.exceptions.ServiceValidationError: Fetch failed with status code 500

---------------
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:797
integration: Home Assistant WebSocket API (documentation, issues)
First occurred: July 21, 2024 at 19:37:06 (7 occurrences)
Last logged: 15:54:45

[281472562727664] Fetch failed with status code 500
[281469690863984] Fetch failed with status code 500
[281469691203872] Fetch failed with status code 500
[281470418659088] Fetch failed with status code 500
[281472240775328] Fetch failed with status code 500

-----------
Logger: homeassistant.helpers.script.websocket_api_script
Source: helpers/script.py:2002
First occurred: July 21, 2024 at 19:37:06 (7 occurrences)
Last logged: 15:54:45

websocket_api script: Error executing script. Error for call_service at pos 1: Fetch failed with status code 500```

**Additional context**
<!-- Add any other context about the problem here. -->

**Comment by valentinfrlch** [comment]
Please add these lines to your `configuration.yaml` to enable debugging:
```yaml
logger:
  logs:
    custom_components.gpt4vision: debug
```
This should log the following line when making a request:
```
Fetching image from <image_url>
```

Can you try to open that url in your browser and see if you can access it? You'll need to be on the same network as your Home Assistant Instance as it is probably going to be some local ip address.

**Comment by yreiter** [comment]
I think I understood what the problem was! The cameras I have are from Nest. When I restarted for Home Assistant, I received a message that the cameras needed to be re-authenticated. That's how it is with Nest's cameras, once a week or so, you must renew access to the cameras (annoying!). Anyway, now it works! Thanks, and sorry I bothered you.

**Comment by valentinfrlch** [comment]
No problem! Glad to hear it's working again!
